# Generated by Django 3.0.3 on 2020-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeconnect',
            name='connected_account_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
