# Generated by Django 3.0.3 on 2020-06-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='payment_method_id',
            new_name='stripe_payment_method_id',
        ),
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='product_id',
            new_name='stripe_product_id',
        ),
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='subscription_id',
            new_name='stripe_subscription_id',
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=32, null=True)),
                ('due_date', models.DateTimeField()),
                ('period_start_date', models.DateTimeField()),
                ('period_end_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=16)),
                ('paid', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.StripeSubscription')),
            ],
        ),
    ]
