# Generated by Django 3.0.3 on 2020-07-12 15:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_supportedcurrency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SiteThemeVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=512)),
                ('binary_value', models.BinaryField(blank=True, null=True)),
                ('variable_type', models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('HEXCOLOR', 'Hex colour code'), ('URL', 'URL'), ('IMAGE', 'Image')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.SiteTheme')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('site_theme', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SiteThemeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.SiteTheme')),
            ],
            options={
                'unique_together': {('site_theme', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SiteThemeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.SiteTheme')),
            ],
            options={
                'unique_together': {('site_theme', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SiteThemeAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=256)),
                ('detected_type', models.CharField(blank=True, max_length=64, null=True)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.SiteTheme')),
            ],
            options={
                'unique_together': {('site_theme', 'name')},
            },
        ),
    ]
