# Generated by Django 3.0.3 on 2020-07-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitethemevariable',
            name='variable_type',
            field=models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('HEXCOLOR', 'Hex colour code'), ('URL', 'URL'), ('IMAGE', 'Image'), ('BOOL', 'Boolean')], max_length=8),
        ),
    ]
