# Generated by Django 3.0.3 on 2020-07-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_auto_20200713_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitethemetemplate',
            name='template_type',
            field=models.CharField(blank=True, choices=[('INDEX', 'Index'), ('PRODUCT', 'Product'), ('PAGE', 'Page')], max_length=16, null=True),
        ),
    ]
