# Generated by Django 3.0.3 on 2020-07-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_sitethemetemplate_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitethemetemplate',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
