# Generated by Django 3.0.3 on 2020-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20200715_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitethemesection',
            name='section_type',
            field=models.CharField(blank=True, choices=[('INDEX', 'Index'), ('PRODUCT', 'Product'), ('PAGE', 'Page')], max_length=16, null=True),
        ),
    ]
