# Generated by Django 3.0.3 on 2020-07-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_sitethemesection_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitethemesection',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
