# Generated by Django 3.0.3 on 2020-07-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_auto_20200715_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitethemeasset',
            name='detected_type',
        ),
        migrations.AddField(
            model_name='sitethemeasset',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('JS', 'Javascript'), ('CSS', 'Javascript'), ('IMG', 'Image'), ('OTHER', 'Other')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sitethemeasset',
            name='content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitethemesection',
            name='section_type',
            field=models.CharField(blank=True, choices=[('BIO', 'Bio'), ('FAQ', 'FAQ'), ('TEXT_WITH_IMAGE', 'Text with image'), ('NEWSLETTER', 'Newsletter'), ('TOC', 'Table of contents'), ('TESTIMONIALS', 'Testimonials'), ('TEXT', 'Text'), ('TEXT_WITH_VIDEO', 'Text with video'), ('CATEGORIES', 'Categories')], max_length=16, null=True),
        ),
    ]
