# Generated by Django 3.0.3 on 2020-07-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_auto_20200716_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitethemeasset',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('JS', 'Javascript'), ('CSS', 'CSS'), ('IMG', 'Image'), ('OTHER', 'Other')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sitethemeasset',
            name='content',
            field=models.BinaryField(blank=True, editable=True, max_length=5120, null=True),
        ),
    ]
