# Generated by Django 3.0.3 on 2020-07-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_auto_20200723_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitethemeasset',
            name='content',
            field=models.BinaryField(blank=True, max_length=5120, null=True),
        ),
    ]
