# Generated by Django 3.0.3 on 2020-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0009_auto_20200729_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitethemesection',
            name='section_type',
            field=models.CharField(blank=True, choices=[('BIO', 'Bio'), ('FAQ', 'FAQ'), ('IMAGE_WITH_TEXT', 'Image with text'), ('NEWSLETTER', 'Newsletter'), ('TOC', 'Table of contents'), ('TESTIMONIALS', 'Testimonials'), ('TEXT', 'Text'), ('VIDEO_WITH_TEXT', 'Video with text'), ('CATEGORIES', 'Categories')], max_length=16, null=True),
        ),
    ]
