# Generated by Django 3.0.3 on 2020-06-09 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200223_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_slug',
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('store_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('vat_address', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('language', models.CharField(default='en', max_length=2)),
                ('subdomain', models.CharField(max_length=256, unique=True)),
                ('custom_domain', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='customer_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Store'),
        ),
    ]
