# Generated by Django 3.0.3 on 2020-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200609_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='subdomain',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
