# Generated by Django 3.0.3 on 2020-06-16 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('new_free_product_email', models.BooleanField(default=True)),
                ('new_sale_email', models.BooleanField(default=True)),
                ('new_membership_email', models.BooleanField(default=True)),
                ('cancel_membership_email', models.BooleanField(default=True)),
                ('new_message_email', models.BooleanField(default=True)),
                ('new_message_app', models.BooleanField(default=True)),
                ('course_comment_email', models.BooleanField(default=True)),
                ('course_completed_email', models.BooleanField(default=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
    ]
