# Generated by Django 3.0.3 on 2020-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notificationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='mailing_address',
        ),
        migrations.AlterField(
            model_name='store',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
