# Generated by Django 3.0.3 on 2020-06-18 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200618_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
