# Generated by Django 3.0.3 on 2020-06-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200621_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='collect_tax_address',
            new_name='collect_tax_addresses',
        ),
    ]
