# Generated by Django 3.0.3 on 2020-06-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200621_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('multiple', models.IntegerField(default=100)),
                ('order', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='store',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
