# Generated by Django 3.0.3 on 2020-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200624_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
