# Generated by Django 3.0.3 on 2020-06-24 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200624_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
