# Generated by Django 3.0.3 on 2020-06-26 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200624_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
