# Generated by Django 3.0.3 on 2020-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_passwordresetkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedcurrency',
            name='format_string',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
