# Generated by Django 3.0.3 on 2020-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_supportedcurrency_format_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedcurrency',
            name='symbol',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
