# Generated by Django 3.0.3 on 2020-07-29 09:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_supportedcurrency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='store',
            name='schema_draft',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
