# Generated by Django 3.0.3 on 2020-08-02 18:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200729_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='store',
            name='schema_draft',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.BinaryField(blank=True, max_length=5120, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
    ]
