# Generated by Django 3.0.3 on 2020-08-17 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200802_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
