# Generated by Django 3.0.3 on 2020-08-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200817_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store'),
        ),
    ]
