# Generated by Django 3.0.3 on 2020-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200817_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
