# Generated by Django 3.0.3 on 2020-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_uploadedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category_section_layout',
            field=models.CharField(choices=[('LIST', 'List'), ('GRID', 'Grid')], default='LIST', max_length=8),
        ),
        migrations.AddField(
            model_name='store',
            name='product_section_layout',
            field=models.CharField(choices=[('LIST', 'List'), ('GRID', 'Grid')], default='LIST', max_length=8),
        ),
    ]
