# Generated by Django 3.0.3 on 2020-06-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='reduction_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percentage')], default='amount', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_usages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
