# Generated by Django 3.0.3 on 2020-06-12 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20200609_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='max_usages',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='reduction',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
