version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_PASSWORD: saastemplate
          POSTGRES_USER: saastemplate
          POSTGRES_DB: saastemplate
        ports:
          - 5432:5432
        volumes:
          - .:/data
      - image: circleci/redis:4-alpine3.10
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app

workflows:
  version: 2
  workflow:
    jobs:
      - build
