# Generated by Django 3.0.3 on 2020-06-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20200618_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMarketingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('double_opt_in', models.BooleanField(default=True)),
                ('opt_in_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
    ]
