# Generated by Django 3.0.3 on 2020-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmarketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmarketingsettings',
            name='opt_in_text',
            field=models.TextField(blank=True, default='I consent to receive updates about more awesome products.', null=True),
        ),
    ]
