# Generated by Django 3.0.3 on 2020-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('STORE', 'Store'), ('USER', 'User')], default='USER', max_length=8),
        ),
    ]
