# Generated by Django 3.0.3 on 2020-06-23 13:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200621_1333'),
        ('messaging', '0002_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('chat_display_as', models.CharField(choices=[('STORE', 'Name of store'), ('USER', "User's full name"), ('CUSTOM', 'Custom value')], default='STORE', max_length=8)),
                ('chat_display_name', models.CharField(blank=True, max_length=64, null=True)),
                ('default_status', models.CharField(choices=[('ONLINE', 'Online'), ('AWAY', 'Away'), ('HIDDEN', 'Hidden')], default='ONLINE', max_length=8)),
                ('chat_available_to', models.CharField(choices=[('NOBODY', 'Nobody'), ('CUSTOMER', 'Customers'), ('STORE', 'Everybody')], default='CUSTOMER', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
    ]
