# Generated by Django 3.0.3 on 2020-06-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='play_sounds',
            field=models.BooleanField(default=True),
        ),
    ]
