# Generated by Django 3.0.3 on 2020-06-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200626_1332'),
        ('products', '0014_membership'),
        ('customers', '0003_auto_20200626_1332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('store', 'customer', 'product')},
        ),
    ]
