# Generated by Django 3.0.3 on 2020-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200626_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accepts_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
