# Generated by Django 3.0.3 on 2020-07-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200708_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='was_free',
            field=models.BooleanField(default=False),
        ),
    ]
