# Generated by Django 3.0.3 on 2020-07-29 09:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='page',
            name='schema_draft',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
