# Generated by Django 3.0.3 on 2020-09-01 10:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_uploadedvideo'),
        ('sites', '0003_auto_20200802_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProductsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('schema_draft', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCategoriesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('schema_draft', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
    ]
