# Generated by Django 3.0.3 on 2020-09-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_globalcategoriessection_globalproductssection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalproductssection',
            name='store',
        ),
        migrations.DeleteModel(
            name='GlobalCategoriesSection',
        ),
        migrations.DeleteModel(
            name='GlobalProductsSection',
        ),
    ]
