# Generated by Django 3.0.3 on 2020-06-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_colour', models.CharField(default='', max_length=6)),
                ('background_colour', models.CharField(default='', max_length=6)),
                ('heading_colour', models.CharField(default='', max_length=6)),
                ('text_colour', models.CharField(default='', max_length=6)),
                ('button_colour', models.CharField(default='', max_length=6)),
                ('button_text_colour', models.CharField(default='', max_length=6)),
                ('heading_font', models.CharField(default='', max_length=64)),
                ('body_font', models.CharField(default='', max_length=64)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
    ]
