# Generated by Django 3.0.3 on 2020-06-03 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200410_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('section', 'Section'), ('text', 'Text'), ('link', 'Link'), ('video', 'Video')], max_length=8),
        ),
    ]
