# Generated by Django 3.0.3 on 2020-06-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200603_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['order', 'parent_item', 'product']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ContentItem'),
        ),
    ]
