# Generated by Django 3.0.3 on 2020-06-07 14:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200604_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contentitem',
            name='editor_content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CloudflareVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cloudflare_uuid', models.CharField(blank=True, max_length=32, null=True)),
                ('upload_url', models.URLField()),
                ('max_duration_seconds', models.IntegerField(default=3600)),
                ('require_signed_urls', models.BooleanField(default=True)),
                ('allowed_origins', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('ready_to_stream', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='contentitem',
            name='cloudflare_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CloudflareVideo'),
        ),
    ]
