# Generated by Django 3.0.3 on 2020-06-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200609_1218'),
        ('products', '0007_auto_20200607_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Store'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('section', 'Section'), ('text', 'Text'), ('file', 'File'), ('link', 'Link'), ('video', 'Video')], max_length=8),
        ),
    ]
