# Generated by Django 3.0.3 on 2020-06-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200612_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='file_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
