# Generated by Django 3.0.3 on 2020-06-14 11:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_contentitem_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentitem',
            old_name='url',
            new_name='presigned_url',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='file_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='presigned_url_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
