# Generated by Django 3.0.3 on 2020-06-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_membership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentitem',
            unique_together={('product', 'parent_item', 'order')},
        ),
    ]
