# Generated by Django 3.0.3 on 2020-07-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200630_1449'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentitem',
            unique_together=set(),
        ),
    ]
