# Generated by Django 3.0.3 on 2020-07-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200712_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_product', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('section', 'Section'), ('text', 'Text'), ('file', 'File'), ('link', 'Link'), ('video', 'Video'), ('product', 'Product')], max_length=8),
        ),
    ]
