# Generated by Django 3.0.3 on 2020-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200723_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
